export const products = [
  {
    title: "Exploring English",
    frontImg: "front-back-title-images/front/1.jpg",
    backImg: "front-back-title-images/back/1.jpg",
    grade: "Nursery",
    subject: "English",
    series: "Green Hills",
    discription: `this is book discription`,
  },
  {
    title: "Exploring English",
    frontImg: "front-back-title-images/front/2.jpg",
    backImg: "front-back-title-images/back/2.jpg",
    grade: "Pre Nursery",
    subject: "English",
    series: "Cornerstone",
    discription: `this is book discription`,
  },
  {
    title: "Exploring English",
    frontImg: "front-back-title-images/front/3.jpg",
    backImg: "front-back-title-images/back/3.jpg",
    grade: "Nursery",
    subject: "English",
    series: "Cornerstone",
    discription: `this is book discription`,
  },
  {
    title: "Exploring English",
    frontImg: "front-back-title-images/front/4.jpg",
    backImg: "front-back-title-images/back/4.jpg",
    grade: "Pre Nursery",
    subject: "English",
    series: "Cornerstone",
    discription: `this is book discription`,
  },
  {
    title: "Exploring English",
    frontImg: "front-back-title-images/front/5.jpg",
    backImg: "front-back-title-images/back/5.jpg",
    grade: "Nursery",
    subject: "Mathametics",
    series: "Cornerstone",
    discription: `this is book discription`,
  },
  {
    title: "Guncha Urdu",
    frontImg: "front-back-title-images/front/6.jpg",
    backImg: "front-back-title-images/back/6.jpg",
    grade: "Pre Nursery",
    subject: "Urdu",
    series: "Cornerstone",
    discription: `this is book discription`,
  },
  {
    title: "Guncha Urdu",
    frontImg: "front-back-title-images/front/7.jpg",
    backImg: "front-back-title-images/back/7.jpg",
    grade: "KG",
    subject: "Urdu",
    series: "Green Hills",
    discription: `this is book discription`,
  },
];
